version: '3'
services:

  flask:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: flask
    image: digitalocean.com/flask-python:3.9.10
    restart: unless-stopped
    environment:
      APP_ENV: "prod"
      APP_DEBUG: "False"
      APP_PORT: 5000
      MONGODB_DATABASE: myappdb
      MONGODB_USERNAME: userdemo
      MONGODB_PASSWORD: Tecsup
      MONGODB_HOSTNAME: mongodb
    ports:
      - "8000:5000"
    volumes:
      - appdata:/var/www
    depends_on:
      - mongodb
    networks:
      - frontend
      - backend

  mongodb:
    image: mongo:4.1.8-xenial
    container_name: mongodb
    restart: unless-stopped
    command: mongod --auth
    environment:
      MONGO_INITDB_ROOT_USERNAME: userdemo
      MONGO_INITDB_ROOT_PASSWORD: Tecsup
      MONGO_INITDB_DATABASE: myappdb
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  frontend:
    driver: bridge
  backend:
    driver: bridge

volumes:
  mongodbdata:
    driver: local
  appdata:
    driver: local
